monitor = eDP-1, preferred, 0x0, 1
monitor = , preferred, -3000x0, 1

env = XCURSOR_THEME,Posy_Cursor_Black
env = XCURSOR_SIZE,24
env = XCURSOR_PATH,~/.icons

exec-once = /home/yktsnet/.config/hypr/scripts/workspace_colors.sh &
exec-once = hyprctl setcursor Posy_Cursor_Black 24
exec-once = swww-daemon
exec-once = swww-random
exec-once = hyprctl dispatch workspace 4

workspace = 4, monitor:eDP-1, default:true, persistent:true
workspace = 5, monitor:eDP-1, persistent:true
workspace = 6, monitor:eDP-1, persistent:true
workspace = 7, monitor:eDP-1, persistent:true

workspace = special:s1, on-created-empty:kitty

bind = SUPER, T, exec, kitty
bind = SUPER, B, exec, firefox

bind = ALT, Space, killactive
bind = SUPER, Return, fullscreen, 0
bind = SUPER, minus, exec, pkill -SIGUSR1 waybar
bind = SUPER SHIFT, A, movewindow, mon:-1
bind = SUPER, F, exec, grim -g "$(slurp)" - | wl-copy
bind = SUPER, S, exec, mkdir -p ~/Downloads && grim -g "$(slurp)" - | tee ~/Downloads/$(date +'%Y%m%d_%H%M%S').png | wl-copy

bindle = , XF86AudioRaiseVolume, exec, /run/current-system/sw/bin/wpctl set-volume -l 1.0 @DEFAULT_AUDIO_SINK@ 5%+
bindle = , XF86AudioLowerVolume, exec, /run/current-system/sw/bin/wpctl set-volume -l 1.0 @DEFAULT_AUDIO_SINK@ 5%-
bindle = , XF86AudioMute, exec, ~/.config/hypr/scripts/mute_handler.sh audio
bindle = , XF86AudioMicMute, exec, ~/.config/hypr/scripts/mute_handler.sh mic
bindle = , XF86MonBrightnessUp, exec, brightnessctl set 5%+
bindle = , XF86MonBrightnessDown, exec, brightnessctl set 5%-

bindle = , F3, exec, /run/current-system/sw/bin/wpctl set-volume -l 1.0 @DEFAULT_AUDIO_SINK@ 5%+
bindle = , F2, exec, /run/current-system/sw/bin/wpctl set-volume -l 1.0 @DEFAULT_AUDIO_SINK@ 5%-
bindle = , F1, exec, ~/.config/hypr/scripts/mute_handler.sh audio
bindle = , F4, exec, ~/.config/hypr/scripts/mute_handler.sh mic
bindle = , F6, exec, brightnessctl set 5%+
bindle = , F5, exec, brightnessctl set 5%-

bind = SUPER, A, focusmonitor, -1

bind = SUPER, Space, cyclenext

bind = SUPER, Tab, togglespecialworkspace, s1

bind = SUPER, Q, workspace, 4
bind = SUPER, W, workspace, 5
bind = SUPER, E, workspace, 6
bind = SUPER, R, workspace, 7

bind = SUPER SHIFT, Q, movetoworkspace, 4
bind = SUPER SHIFT, W, movetoworkspace, 5
bind = SUPER SHIFT, E, movetoworkspace, 6
bind = SUPER SHIFT, R, movetoworkspace, 7

bindm = SUPER, mouse:272, movewindow
bindm = SUPER, mouse:273, resizewindow

general {
  gaps_in = 3
  gaps_out = 15
  border_size = 2
  col.active_border = rgba(a6accdff)
  col.inactive_border = rgba(1b1e28ff)
  layout = dwindle
}

decoration {
  rounding = 10
  active_opacity = 0.98
  inactive_opacity = 0.80
  shadow {
    enabled = true
    range = 25
    render_power = 4
    color = rgba(1b1e2899)
    offset = 0, 4
  }
  blur {
    enabled = true
    size = 6
    passes = 2
    new_optimizations = true
    xray = true
    ignore_opacity = true
  }
}

animations {
  enabled = true
  bezier = focusBezier, 0.2, 1, 0.2, 1
  animation = windows, 1, 5, focusBezier
  animation = windowsOut, 1, 5, default, popin 80%
  animation = border, 1, 5, default
  animation = fade, 1, 5, default
  animation = workspaces, 1, 5, default
}

windowrule = match:title ^(ranger)$, float on, size 85% 85%, center on, stay_focused on
windowrule = match:title ^(.*Brave.*)$, opacity 1.0 override 1.0 override, opaque on
windowrule = match:class ^(firefox)$, opacity 1.0 override 1.0 override
windowrule = match:title ^(.*Firefox.*)$, opacity 1.0 override 1.0 override, opaque on

input {
  kb_layout = us
  touchpad {
    natural_scroll = true
  }
}

misc {
  force_default_wallpaper = 0
  disable_hyprland_logo = true
  disable_splash_rendering = true
}
